orders/urls.py
from django.urls import path
from .views import add_to_cart,order_list,checkout

app_name = 'orders'

urlpatterns = [
    path('add_to_cart',add_to_cart,name="add_to_cart"),
    path("", order_list, name="order_list"),
    path("checkout", checkout, name="checkout"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/',include('products.urls', namespace='products')),
    path('orders/',include('orders.urls', namespace='orders')),
    path('summernote/', include('django_summernote.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cart_include.html
      <div class="cart-header">
        <div class="cart-total">
          <i class="fas fa-shopping-basket"></i>
          <span>total item ({{cart|length}})</span>
        </div>
        <button class="cart-close"><i class="icofont-close"></i></button>
      </div>
      <ul class="cart-list">
      {% for item in cart_data.cart_detail.all %}
        <li class="cart-item">
          <div class="cart-media">
            <a href="#"
              ><img src="{{item.product.image.url}}" alt="product"
            /></a>
            <button class="cart-delete">
              <i class="far fa-trash-alt"></i>
            </button>
          </div>
          <div class="cart-info-group">
            <div class="cart-info">
              <h6><a href="product-single.html">{{item.product}}</a></h6>
              <p>Unit Price - ${{item.price}}</p>
            </div>
            <div class="cart-action-group">
              <div class="product-action">
                <button class="action-minus" title="Quantity Minus">
                  <i class="icofont-minus"></i>
                </button>
                <input
                  class="action-input"
                  title="Quantity Number"
                  type="text"
                  name="quantity"
                  value="{{item.quantity}}"
                />
                <button class="action-plus" title="Quantity Plus">
                  <i class="icofont-plus"></i>
                </button>
              </div>
              <h6>${{item.total}}</h6>
            </div>
          </div>
        </li>
      {% endfor %}
      </ul>
      <div class="cart-footer">
        <button class="coupon-btn">Do you have a coupon code?</button>
        <form class="coupon-form">
          <input type="text" placeholder="Enter your coupon code" />
          <button type="submit"><span>apply</span></button>
        </form>
        <a class="cart-checkout-btn" href="{% url 'orders:checkout' %}">
          <span class="checkout-label">Proceed to Checkout</span>
          <span class="checkout-price">${{cart_data.get_total}}</span>
        </a>
      </div>